export const menuItems = [
	{
		id: 1,
		name: 'Empanadas',
		description: 'Empanadas tradicionales argentinas.',
		price: 1300,
		category: 'Comidas',
		image: 'https://source.unsplash.com/random/900x700/?empanadas',
	},
	{
		id: 2,
		name: 'Asado',
		description: 'Clásico asado argentino con carne de primera calidad.',
		price: 2500,
		category: 'Comidas',
		image: 'https://source.unsplash.com/random/900x700/?asado',
	},
	{
		id: 3,
		name: 'Milanesa',
		description: 'Milanesa de ternera con papas fritas.',
		price: 700,
		category: 'Comidas',
		image: 'https://source.unsplash.com/random/900x700/?milanesa',
	},
	{
		id: 4,
		name: 'Provoleta',
		description: 'Queso provolone a la parrilla con tomates asados.',
		price: 1500,
		category: 'Comidas',
		image: 'https://source.unsplash.com/random/900x700/?provoleta',
	},
	{
		id: 5,
		name: 'Fernet with Coke',
		description: 'Traditional Argentine drink made with Fernet and Coca-Cola.',
		price: 700,
		category: 'Bebidas',
		image: 'https://source.unsplash.com/random/900x700/?fernet',
	},
	{
		id: 6,
		name: 'Mate',
		description: 'Traditional Argentine infusion prepared with yerba mate.',
		price: 600,
		category: 'Bebidas',
		image: 'https://source.unsplash.com/random/900x700/?mate',
	},
	{
		id: 7,
		name: 'Craft Beer',
		description: 'Locally brewed craft beer.',
		price: 800,
		category: 'Bebidas',
		image: 'https://source.unsplash.com/random/900x700/?beer',
	},
	{
		id: 8,
		name: 'Malbec Wine',
		description: 'High-quality Argentine Malbec red wine.',
		price: 900,
		category: 'Bebidas',
		image: 'https://source.unsplash.com/random/900x700/?wine',
	},
	{
		id: 9,
		name: 'Mojito',
		description: 'Refreshing cocktail made with rum, mint, and lime.',
		price: 1100,
		category: 'Bebidas',
		image: 'https://source.unsplash.com/random/900x700/?mojito',
	},
	{
		id: 10,
		name: 'Dulce de Leche',
		description: 'Argentine dessert made with milk and sugar.',
		price: 1200,
		category: 'Postres',
		image: 'https://source.unsplash.com/random/900x700/?dulce+de+leche',
	},
];
